//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digiwin.Chun.Common.Tools.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Digiwin.Chun.Common.Tools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 客户端正在运行 的本地化字符串。
        /// </summary>
        internal static string ClientRunning {
            get {
                return ResourceManager.GetString("ClientRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源码 的本地化字符串。
        /// </summary>
        internal static string CodeSource {
            get {
                return ResourceManager.GetString("CodeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制失败 的本地化字符串。
        /// </summary>
        internal static string CopyFailed {
            get {
                return ResourceManager.GetString("CopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 借用Typekey源码和配置不存在 的本地化字符串。
        /// </summary>
        internal static string CopyResourceNotExisted {
            get {
                return ResourceManager.GetString("CopyResourceNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制成功 !!! 的本地化字符串。
        /// </summary>
        internal static string CopySucess {
            get {
                return ResourceManager.GetString("CopySucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create{0} 的本地化字符串。
        /// </summary>
        internal static string CreateFileName {
            get {
                return ResourceManager.GetString("CreateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称不可为空 的本地化字符串。
        /// </summary>
        internal static string CustomerNameNotNull {
            get {
                return ResourceManager.GetString("CustomerNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录已存在，是否覆盖?? 的本地化字符串。
        /// </summary>
        internal static string DirExisted {
            get {
                return ResourceManager.GetString("DirExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹{0}不存在，请查看！！！ 的本地化字符串。
        /// </summary>
        internal static string DirNotExisted {
            get {
                return ResourceManager.GetString("DirNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前DLL被占用，是否结束进程以复制？ 的本地化字符串。
        /// </summary>
        internal static string DllUsedMsg {
            get {
                return ResourceManager.GetString("DllUsedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已启动！ 的本地化字符串。
        /// </summary>
        internal static string ExeAlreadyExe {
            get {
                return ResourceManager.GetString("ExeAlreadyExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动应用程序时出错！原因： 的本地化字符串。
        /// </summary>
        internal static string ExeExeError {
            get {
                return ResourceManager.GetString("ExeExeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件{0}已复制，是否覆盖？ 的本地化字符串。
        /// </summary>
        internal static string FileAlreadyCopy {
            get {
                return ResourceManager.GetString("FileAlreadyCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件已存在，是否覆盖？ 的本地化字符串。
        /// </summary>
        internal static string FileExisted {
            get {
                return ResourceManager.GetString("FileExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成成功 的本地化字符串。
        /// </summary>
        internal static string GenerateSucess {
            get {
                return ResourceManager.GetString("GenerateSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助文档不存在！ 的本地化字符串。
        /// </summary>
        internal static string HelpDocNotExiested {
            get {
                return ResourceManager.GetString("HelpDocNotExiested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未指定模块信息或模块名 的本地化字符串。
        /// </summary>
        internal static string ModuleNotExisted {
            get {
                return ResourceManager.GetString("ModuleNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无copy资源 的本地化字符串。
        /// </summary>
        internal static string NoCopySource {
            get {
                return ResourceManager.GetString("NoCopySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到 的本地化字符串。
        /// </summary>
        internal static string NotFind {
            get {
                return ResourceManager.GetString("NotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到文件{0} 的本地化字符串。
        /// </summary>
        internal static string NotFindFile {
            get {
                return ResourceManager.GetString("NotFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不可为空 的本地化字符串。
        /// </summary>
        internal static string notNull {
            get {
                return ResourceManager.GetString("notNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开Word文档出错 的本地化字符串。
        /// </summary>
        internal static string OpenDocError {
            get {
                return ResourceManager.GetString("OpenDocError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 借用目录不存在！ 的本地化字符串。
        /// </summary>
        internal static string PkgDirNotExisted {
            get {
                return ResourceManager.GetString("PkgDirNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 借用TypeKey不可为空 的本地化字符串。
        /// </summary>
        internal static string pkgNotNull {
            get {
                return ResourceManager.GetString("pkgNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取实体文件时发生错误 的本地化字符串。
        /// </summary>
        internal static string ReadEntityError {
            get {
                return ResourceManager.GetString("ReadEntityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务端未启动 的本地化字符串。
        /// </summary>
        internal static string ServerNotRunning {
            get {
                return ResourceManager.GetString("ServerNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务端正在运行 的本地化字符串。
        /// </summary>
        internal static string ServerRunning {
            get {
                return ResourceManager.GetString("ServerRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}/{1}模板不存在，请检查 的本地化字符串。
        /// </summary>
        internal static string TemplateNotExisted {
            get {
                return ResourceManager.GetString("TemplateNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入创建地址及名称 的本地化字符串。
        /// </summary>
        internal static string TypekeyNotExisted {
            get {
                return ResourceManager.GetString("TypekeyNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string WarningMsg {
            get {
                return ResourceManager.GetString("WarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否 的本地化字符串。
        /// </summary>
        internal static string WhetherOrNot {
            get {
                return ResourceManager.GetString("WhetherOrNot", resourceCulture);
            }
        }
    }
}
