//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSTool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 本次操作将清空新增页面选择项，你确定这样做吗？ 的本地化字符串。
        /// </summary>
        internal static string ClearMsg {
            get {
                return ResourceManager.GetString("ClearMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制成功 !!! 的本地化字符串。
        /// </summary>
        internal static string CopySucess {
            get {
                return ResourceManager.GetString("CopySucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目錄已存在，是否覆蓋?? 的本地化字符串。
        /// </summary>
        internal static string DirExisted {
            get {
                return ResourceManager.GetString("DirExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹{0}不存在，请查看！！！ 的本地化字符串。
        /// </summary>
        internal static string DirNotExist {
            get {
                return ResourceManager.GetString("DirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前DLL被占用，是否结束进程以复制？ 的本地化字符串。
        /// </summary>
        internal static string DllUsedMsg {
            get {
                return ResourceManager.GetString("DllUsedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成成功 !!! 的本地化字符串。
        /// </summary>
        internal static string GenerateSucess {
            get {
                return ResourceManager.GetString("GenerateSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准代码{0}不存在 的本地化字符串。
        /// </summary>
        internal static string PKGNotExisted {
            get {
                return ResourceManager.GetString("PKGNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入创建地址及名称 的本地化字符串。
        /// </summary>
        internal static string TypeKeyNotExisted {
            get {
                return ResourceManager.GetString("TypeKeyNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warnning 的本地化字符串。
        /// </summary>
        internal static string WarnningMsg {
            get {
                return ResourceManager.GetString("WarnningMsg", resourceCulture);
            }
        }
    }
}
